
server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters: # ?? ??? ??? ????? ?????.
        - name: GlobalFilter
          args:
            baseMessage: GlobalFilterTest
            preLogger: true
            postLogger: true
      routes:
        - id: user-service #???? id??
          uri: lb://USER-SERVICE #???? ??? ???? ??
          predicates:
            - Path=/user/** # ?? ???? ??? ?? ? ??
          filters:
            - JwtFilter # jwt ?? ??

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://34.64.69.238:8761/eureka #????? ??? ?
