
server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://localhost:3001
              - http://34.125.119.98:3000
              - http://34.125.119.98:3001
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - name: GlobalFilter
          args:
            baseMessage: GlobalFilterTest
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: class-service
          uri: lb://CLASS-SERVICE
          predicates:
            - Path=/class/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://34.64.69.238:8761/eureka
